compressionLevel: mixed

enableGlobalCache: false

npmScopes:
  xx.network:
    npmRegistryServer: "https://registry.npmjs.org"

enableImmutableInstalls: false

enableProgressBars: false

logFilters:
  - code: YN0013
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.6.0.cjs
